# Generated by Django 4.2 on 2023-05-12 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_aggregator', '0002_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
